# Generated by Django 3.0.6 on 2020-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('bus_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Bus Number')),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('places', models.TextField(help_text='Comman Separated Value', verbose_name='Places')),
                ('time', models.TextField(help_text='Comman Separated Value', verbose_name='Time')),
                ('CurrentLocation', models.CharField(blank=True, default='', max_length=100, verbose_name='Current Location')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
