# Generated by Django 3.0.6 on 2020-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='startTime',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
