# Generated by Django 3.0.6 on 2020-05-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstName', models.CharField(max_length=60, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=60, verbose_name='Last Name')),
                ('reg_no', models.BigIntegerField(help_text='It is the registration number allocated by BPUT', primary_key=True, serialize=False, unique=True, verbose_name='Registration Number')),
                ('college_id', models.CharField(help_text='It is the college assigned Roll No.', max_length=8, unique=True, verbose_name='College Roll No')),
                ('email', models.EmailField(help_text='Enter Your E-Mail', max_length=254, verbose_name='E-Mail')),
                ('mobile1', models.BigIntegerField(help_text='Enter your Personal Contact', unique=True, verbose_name='Personal Contact')),
                ('yoj', models.DateField(help_text='Select your year of join the college', verbose_name='YOJ')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
