# Generated by Django 3.0.6 on 2020-05-13 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile1',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='student',
            name='authAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studAcc', to=settings.AUTH_USER_MODEL, verbose_name='Authenticate Account'),
            preserve_default=False,
        ),
    ]
